apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-zk-pv01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/container_data/zookeeper/pv1
    server: 172.23.5.87

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-zk-pv02
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/container_data/zookeeper/pv2
    server: 172.23.5.87

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-zk-pv03
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/container_data/zookeeper/pv3
    server: 172.23.5.87
